#' MW catchment variables
  #'
  #' A dataset containing the catchment id and other attributes for 12319 sub-catchments
  #' around the Melbourne region in southeastern Australia. Also includes the SEGMENTNO
  #' identifier from the Australian Geofabric to link the MW subcatchments to geofabric
  #' environmental attributes
  #'
  #' @format A data frame with 12319 rows and 54 variables:
     #'\describe{
#'\item{site}{}
#'\item{AREA}{}
#'\item{PERIMETER}{}
#'\item{NEXTDS}{}
#'\item{SCAREA}{}
#'\item{SCTIA}{}
#'\item{SCDAI9A}{}
#'\item{CAREA}{}
#'\item{DAI9A}{}
#'\item{TIA}{}
#'\item{DAI9}{}
#'\item{TI}{}
#'\item{SCB20A}{}
#'\item{SCB40A}{}
#'\item{SCSTRLEN}{}
#'\item{STRLEN}{}
#'\item{B20A}{}
#'\item{B40A}{}
#'\item{STRLEN_SKM}{}
#'\item{sub_unq_id}{}
#'\item{segmentno}{}
#'\item{elev}{}
#'\item{FexpL50W15}{}
#'\item{buffL30W30}{}
#'\item{buffL30W10}{}
#'\item{RUNANNMEAN}{}
#'\item{RUNMINANNT}{}
#'\item{RUNPCTL5}{}
#'\item{RUNPCTL10}{}
#'\item{RUNPCTL20}{}
#'\item{RUNPCTL30}{}
#'\item{RUNPCTL40}{}
#'\item{RUNPCTL50}{}
#'\item{RUNPCTL60}{}
#'\item{RUNPCTL70}{}
#'\item{RUNPCTL80}{}
#'\item{RUNPCTL90}{}
#'\item{RUNPCTL95}{}
#'\item{RUNMAXANNT}{}
#'\item{RUNMTHCOFV}{}
#'\item{RUNANNCOFV}{}
#'\item{RUNSUMMERM}{}
#'\item{RUNAUTUMNM}{}
#'\item{RUNWINTERM}{}
#'\item{RUNSPRINGM}{}
#'\item{RUNJAN}{}
#'\item{RUNFEB}{}
#'\item{RUNMAR}{}
#'\item{RUNAPR}{}
#'\item{RUNMAY}{}
#'\item{RUNJUN}{}
#'\item{RUNJUL}{}
#'\item{RUNAUG}{}
#'\item{RUNSEP}{}
#'\item{RUNOCT}{}
#'\item{RUNNOV}{}
#'\item{RUNDEC}{}
#'\item{RUNSKEWNES}{}
#'\item{RUNPERENIA}{}
#'\item{RUNJANCV}{}
#'\item{RUNFEBCV}{}
#'\item{RUNMARCV}{}
#'\item{RUNAPRCV}{}
#'\item{RUNMAYCV}{}
#'\item{RUNJUNCV}{}
#'\item{RUNJULCV}{}
#'\item{RUNAUGCV}{}
#'\item{RUNSEPCV}{}
#'\item{RUNOCTCV}{}
#'\item{RUNNOVCV}{}
#'\item{RUNDECCV}{}
#'\item{RUNMEANMIN}{}
#'\item{RUNMEANMAX}{}
#'\item{RUNCVMINMT}{}
#'\item{RUNCVMAXMT}{}
#'\item{CATSNOW}{}
#'\item{ANRUNDEPTH}{}
#'\item{RUNANNDEP}{}
#'\item{carea.o}{}
#'\item{NOFWBARSUM}{}
#'\item{WFWBARSUM}{}
#'}
#' @source Chris Walsh, University of Melbourne
"mw.catchvars"
