#' MW Fish Survey Data
             #'
             #'Fish
             #'
             #' @format A data frame with 4234 fish surveys:
             #'\describe{
#'\item{DATE}{}
#'\item{YEAR}{}
#'\item{SITE}{}
#'\item{LONGMOD}{}
#'\item{LATMOD}{}
#'\item{WATERBODY}{}
#'\item{ACANBUTC}{}
#'\item{ACANFLAV}{}
#'\item{ACANSPIL}{}
#'\item{ACENPFLA}{}
#'\item{AFURTAMA}{}
#'\item{ALDRFORS}{}
#'\item{AMARLACU}{}
#'\item{AMMOROST}{}
#'\item{ANGUAUST}{}
#'\item{ANGUREIN}{}
#'\item{ARENBIFR}{}
#'\item{ARENFREN}{}
#'\item{ARGYJAPO}{}
#'\item{ARRIGEOR}{}
#'\item{ARRITRUT}{}
#'\item{ATHEMICR}{}
#'\item{BOXFISH}{}
#'\item{CALLMILI}{}
#'\item{CARAAURA}{}
#'\item{CHELLONG}{}
#'\item{CHERDEST}{}
#'\item{CHERSPP}{}
#'\item{CHRYAURA}{}
#'\item{CRATSTER}{}
#'\item{CYPRCARP}{}
#'\item{CYPRSPP}{}
#'\item{DACTNIGR}{}
#'\item{DIPTWHIT}{}
#'\item{ENGACUNI}{}
#'\item{ENGALAEV}{}
#'\item{ENGAQUAD}{}
#'\item{ENGASPP}{}
#'\item{ENGRAUST}{}
#'\item{ENOPARMA}{}
#'\item{EUASKERS}{}
#'\item{EUASSPP}{}
#'\item{EUASWOIW}{}
#'\item{EUASYARR}{}
#'\item{EUPRTASM}{}
#'\item{FAVOLATE}{}
#'\item{FAVOTAMA}{}
#'\item{GADOMARM}{}
#'\item{GALABREV}{}
#'\item{GALAMACU}{}
#'\item{GALAOLID}{}
#'\item{GALAPUSI}{}
#'\item{GALASPP}{}
#'\item{GALATRUT}{}
#'\item{GAMBHOLB}{}
#'\item{GEOTAUST}{}
#'\item{GIRETRIC}{}
#'\item{GOBISEMI}{}
#'\item{GOBISPP}{}
#'\item{GYMNMARM}{}
#'\item{HETEWILS}{}
#'\item{HYPEVITT}{}
#'\item{HYPOMELA}{}
#'\item{HYPSKLUN}{}
#'\item{HYPSSPP}{}
#'\item{KESTESOX}{}
#'\item{LATECALC}{}
#'\item{LEPTPRES}{}
#'\item{LIZAARGE}{}
#'\item{LOVESEAL}{}
#'\item{MACCPEEL}{}
#'\item{MACQAMBI}{}
#'\item{MACQAUST}{}
#'\item{MACQCOLO}{}
#'\item{MACQNOVE}{}
#'\item{MEUSFREY}{}
#'\item{MISGANGU}{}
#'\item{MORDMORD}{}
#'\item{MUGICEPH}{}
#'\item{MUGIPLAT}{}
#'\item{MUSTANTA}{}
#'\item{NANNAUST}{}
#'\item{NANNOBSC}{}
#'\item{NANNSPP}{}
#'\item{NEOCCLEA}{}
#'\item{NEOOBALT}{}
#'\item{NOFISH}{}
#'\item{OMOBANOL}{}
#'\item{ONCOMYKI}{}
#'\item{PARAAUST}{}
#'\item{PARASPP}{}
#'\item{PERCFLUV}{}
#'\item{PHILGRAN}{}
#'\item{PHILMACR}{}
#'\item{PHILSPP}{}
#'\item{PLATBASS}{}
#'\item{PLATLAEV}{}
#'\item{PLATSPEC}{}
#'\item{PRAWN}{}
#'\item{PROTMARA}{}
#'\item{PSEUGEOR}{}
#'\item{PSEUOLOR}{}
#'\item{PSEUSPIN}{}
#'\item{PSEUURVI}{}
#'\item{PSEUWRIG}{}
#'\item{PSEUSPP}{}
#'\item{PUGNCURT}{}
#'\item{REDIMACR}{}
#'\item{RETRSEMO}{}
#'\item{RHOMTAPI}{}
#'\item{RUTIRUTI}{}
#'\item{SALMTRUT}{}
#'\item{SARDSAGA}{}
#'\item{SILLPUNC}{}
#'\item{SIPHCEPH}{}
#'\item{SPHYNOVA}{}
#'\item{SPRAROBU}{}
#'\item{STIGARGU}{}
#'\item{STIGNIGR}{}
#'\item{TANDTAND}{}
#'\item{TASMLAST}{}
#'\item{TETRGLAB}{}
#'\item{THALADEL}{}
#'\item{TINCTINC}{}
#'\item{TRIDTRIG}{}
#'}
#' @source MW
"mw.fish.pa"
